### ISSUE TITLE
How to give AWS credentials?

### ISSUE THREAD

**Issue by mrdlmndr** [awslabs/aws-big-data-blog#11]
Hi,

According to documentation, **KinesisSpout** method constructs an instance of the spout, using AWS credentials. But how and where  I have to give those AWS access and secret key. I could not find any file, where I'v to give.

Please help. Thanks !!!

**Comment by mrdlmndr** [comment]
Solved. Thanks.

**Comment by IanMeyers** [comment]
Hello,

Sorry to hear you had this issue. We've recently updated the code to support the DefaultCredentialsProviderChain, rather than the previous version which was only supported on EC2. If you need more information on supplying credentials, please see http://docs.aws.amazon.com/java-sdk/latest/developer-guide/credentials.html.
